### ISSUE TITLE
BOM details

### ISSUE THREAD

**Issue by Pixelbrick** [eflukx/Stepcraft-GRBLizer#2]
Hi, 

Thanks very much for sharing this. I work as a technician in a university makerspace & we're looking to put together a few of these boards for the routers we have here. 

Could you let us know which TVS suppression diodes & poly-fuse you recommend please? Other stuff we can easily swap out for what we can get/have on hand. 

Cheers,
Jay

**Comment by eflukx** [comment]
Ha.. it has been a loong time since I touched this project.. 😄  (I'm still using my first version in my Stepcraft 840 :))
One thing i recalled that there was a problem in the footprint of the aux TRS connectors.. (pins 3 and 1 swapped), so the `gnd` is connected to the `R`ing of the TRS connector in stead of the `S`leeve. Allow me to update the board for you! :)

![image](https://user-images.githubusercontent.com/996191/202158298-4df11298-0ff7-4e66-b83f-c029337ff4d7.png)


About those (TVS) diodes, I don't think these are too critical, but I will include a type nr in the BOM.

**Comment by Pixelbrick** [comment]
Oh wow! 

I didn't expect a response, let alone an incredibly helpful one in minutes :)

Cheers, 
Jay

**Comment by eflukx** [comment]
I fixed the pinning issue with the output jacks and made some remarks on the schematic. Also made some changes (improvements hopefully) to the routing.
(This is was a Kicad 4 project, made the updates using Kicad 5, but should work fine now in v6 as well)

**Comment by Pixelbrick** [comment]
That's brilliant. 

Much appreciated, 
Jay
